package com.interval.dao.models;

// Generated Aug 12, 2015 7:36:52 PM by Hibernate Tools 3.4.0.CR1

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private Integer id;
	private Product product;
	private Integer availableQuantity;
	private Integer safetyStock;
	private Boolean availability;

	public Inventory() {
	}

	public Inventory(Product product) {
		this.product = product;
	}

	public Inventory(Product product, Integer availableQuantity,
			Integer safetyStock, Boolean availability) {
		this.product = product;
		this.availableQuantity = availableQuantity;
		this.safetyStock = safetyStock;
		this.availability = availability;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getAvailableQuantity() {
		return this.availableQuantity;
	}

	public void setAvailableQuantity(Integer availableQuantity) {
		this.availableQuantity = availableQuantity;
	}

	public Integer getSafetyStock() {
		return this.safetyStock;
	}

	public void setSafetyStock(Integer safetyStock) {
		this.safetyStock = safetyStock;
	}

	public Boolean getAvailability() {
		return this.availability;
	}

	public void setAvailability(Boolean availability) {
		this.availability = availability;
	}

}
