package com.interval.dao.models;

// Generated Aug 12, 2015 7:36:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InventoryTransaction generated by hbm2java
 */
public class InventoryTransaction implements java.io.Serializable {

	private Integer id;
	private TransactionType transactionType;
	private Product product;
	private Date createdTime;
	private Date updatedTime;

	public InventoryTransaction() {
	}

	public InventoryTransaction(TransactionType transactionType, Product product) {
		this.transactionType = transactionType;
		this.product = product;
	}

	public InventoryTransaction(TransactionType transactionType,
			Product product, Date createdTime, Date updatedTime) {
		this.transactionType = transactionType;
		this.product = product;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
