package com.interval.dao.models;

// Generated Aug 13, 2015 3:14:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private Integer id;
	private OrderDetail orderDetail;
	private Date createdTime;
	private Date updatedTime;

	public Invoice() {
	}

	public Invoice(OrderDetail orderDetail) {
		this.orderDetail = orderDetail;
	}

	public Invoice(OrderDetail orderDetail, Date createdTime, Date updatedTime) {
		this.orderDetail = orderDetail;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public OrderDetail getOrderDetail() {
		return this.orderDetail;
	}

	public void setOrderDetail(OrderDetail orderDetail) {
		this.orderDetail = orderDetail;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
