package com.interval.dao.models;

// Generated Aug 12, 2015 7:36:52 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderItem generated by hbm2java
 */
public class OrderItem implements java.io.Serializable {

	private OrderItemId id;
	private OrderDetail orderDetail;
	private Product product;
	private Integer quantity;

	public OrderItem() {
	}

	public OrderItem(OrderItemId id, OrderDetail orderDetail, Product product) {
		this.id = id;
		this.orderDetail = orderDetail;
		this.product = product;
	}

	public OrderItem(OrderItemId id, OrderDetail orderDetail, Product product,
			Integer quantity) {
		this.id = id;
		this.orderDetail = orderDetail;
		this.product = product;
		this.quantity = quantity;
	}

	public OrderItemId getId() {
		return this.id;
	}

	public void setId(OrderItemId id) {
		this.id = id;
	}

	public OrderDetail getOrderDetail() {
		return this.orderDetail;
	}

	public void setOrderDetail(OrderDetail orderDetail) {
		this.orderDetail = orderDetail;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
