package com.interval.dao.models;

// Generated Aug 12, 2015 7:36:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public OrderStatus() {
	}

	public OrderStatus(String name, Set<OrderDetail> orderDetails) {
		this.name = name;
		this.orderDetails = orderDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
