package com.interval.dao.models;

// Generated Aug 13, 2015 3:14:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private VendorCenter vendorCenter;
	private Category category;
	private String name;
	private String description;
	private byte[] image;
	private Date createdTime;
	private Date updatedTime;
	private Set<Inventory> inventories = new HashSet<Inventory>(0);
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<InventoryTransaction> inventoryTransactions = new HashSet<InventoryTransaction>(
			0);

	public Product() {
	}

	public Product(VendorCenter vendorCenter, Category category) {
		this.vendorCenter = vendorCenter;
		this.category = category;
	}

	public Product(VendorCenter vendorCenter, Category category, String name,
			String description, byte[] image, Date createdTime,
			Date updatedTime, Set<Inventory> inventories,
			Set<OrderItem> orderItems,
			Set<InventoryTransaction> inventoryTransactions) {
		this.vendorCenter = vendorCenter;
		this.category = category;
		this.name = name;
		this.description = description;
		this.image = image;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.inventories = inventories;
		this.orderItems = orderItems;
		this.inventoryTransactions = inventoryTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VendorCenter getVendorCenter() {
		return this.vendorCenter;
	}

	public void setVendorCenter(VendorCenter vendorCenter) {
		this.vendorCenter = vendorCenter;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public Set<InventoryTransaction> getInventoryTransactions() {
		return this.inventoryTransactions;
	}

	public void setInventoryTransactions(
			Set<InventoryTransaction> inventoryTransactions) {
		this.inventoryTransactions = inventoryTransactions;
	}

}
