package com.interval.dao.models;

// Generated Aug 14, 2015 6:24:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Screen generated by hbm2java
 */
public class Screen implements java.io.Serializable {

	private Integer id;
	private Center center;
	private String name;
	private Date createdTime;
	private Date updatedTime;
	private Set<Show> shows = new HashSet<Show>(0);

	public Screen() {
	}

	public Screen(Center center, String name, Date createdTime, Date updatedTime) {
		this.center = center;
		this.name = name;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public Screen(Center center, String name, Date createdTime,
			Date updatedTime, Set<Show> shows) {
		this.center = center;
		this.name = name;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.shows = shows;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Center getCenter() {
		return this.center;
	}

	public void setCenter(Center center) {
		this.center = center;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Set<Show> getShows() {
		return this.shows;
	}

	public void setShows(Set<Show> shows) {
		this.shows = shows;
	}

}
