package com.interval.dao.models;

// Generated Aug 14, 2015 6:24:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Show generated by hbm2java
 */
public class Show implements java.io.Serializable {

	private Integer id;
	private Screen screen;
	private Date time;
	private Date createdTime;
	private Date updatedTime;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public Show() {
	}

	public Show(Screen screen, Date time, Date createdTime, Date updatedTime) {
		this.screen = screen;
		this.time = time;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public Show(Screen screen, Date time, Date createdTime, Date updatedTime,
			Set<OrderDetail> orderDetails) {
		this.screen = screen;
		this.time = time;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.orderDetails = orderDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Screen getScreen() {
		return this.screen;
	}

	public void setScreen(Screen screen) {
		this.screen = screen;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
