package com.interval.dao.models;

// Generated Aug 14, 2015 6:24:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);
	private Set<InventoryTransaction> inventoryTransactions = new HashSet<InventoryTransaction>(
			0);

	public TransactionType() {
	}

	public TransactionType(String name, String description,
			Set<Transaction> transactions,
			Set<InventoryTransaction> inventoryTransactions) {
		this.name = name;
		this.description = description;
		this.transactions = transactions;
		this.inventoryTransactions = inventoryTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

	public Set<InventoryTransaction> getInventoryTransactions() {
		return this.inventoryTransactions;
	}

	public void setInventoryTransactions(
			Set<InventoryTransaction> inventoryTransactions) {
		this.inventoryTransactions = inventoryTransactions;
	}

}
