package com.interval.dao.models;

// Generated Aug 12, 2015 7:36:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<InventoryTransaction> inventoryTransactions = new HashSet<InventoryTransaction>(
			0);
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public TransactionType() {
	}

	public TransactionType(String name,
			Set<InventoryTransaction> inventoryTransactions,
			Set<Transaction> transactions) {
		this.name = name;
		this.inventoryTransactions = inventoryTransactions;
		this.transactions = transactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<InventoryTransaction> getInventoryTransactions() {
		return this.inventoryTransactions;
	}

	public void setInventoryTransactions(
			Set<InventoryTransaction> inventoryTransactions) {
		this.inventoryTransactions = inventoryTransactions;
	}

	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
