package com.interval.dao.models;

// Generated Aug 14, 2015 6:24:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VendorCenter generated by hbm2java
 */
public class VendorCenter implements java.io.Serializable {

	private Integer id;
	private Center center;
	private Vendor vendor;
	private Set<Product> products = new HashSet<Product>(0);

	public VendorCenter() {
	}

	public VendorCenter(Center center, Vendor vendor) {
		this.center = center;
		this.vendor = vendor;
	}

	public VendorCenter(Center center, Vendor vendor, Set<Product> products) {
		this.center = center;
		this.vendor = vendor;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Center getCenter() {
		return this.center;
	}

	public void setCenter(Center center) {
		this.center = center;
	}

	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
